Paged queries
rhit-corridg/rc-website-server pull request #36
Opened 2023-02-12 22:11 UTC by TheGamerzs

2023-02-13 05:14 UTC, rhit-corridg requested changes
I like how this looks but that rank column is a big nono. We have to find some other way to order by rank that doesn't involve a concrete column in the database. I think some libraries support computed columns which would let us get the sum of their turned in vouchers and we could just use the index of the member to calculate the rank to pass to the front end. 

If computed columns aren't an option there are also subqueries/joins that we could use to get the total number of vouchers turned in.

Our absolute last choice is we add a column to the members table that is simply "total_vouchers" that we update whenever when they turn in vouchers. I already don't like how we keep track of a number in the rts and pigs table instead of just calculating it from the payouts table though and I'd like to keep duplicated data to a minimum.

2023-02-13 05:14 UTC, gabotaco commented on app/graphql/resolvers/PagedQueries/GetPaginatedAllMemberDetails.js
> +										}
I believe graphql has a "contains" filter

2023-02-13 05:14 UTC, gabotaco commented on app/graphql/resolvers/PagedQueries/GetPaginatedAllMemberDetails.js
> +					order: args.order ? args.order : [['rank', 'ASC']],
Instead of ordering by a 'rank' column, maybe try to find a way to make a computed column that is the sum of rts and pigs vouchers? Or possibly just don't order it at all and sort it after the query is over

2023-02-13 05:14 UTC, gabotaco commented on app/graphql/resolvers/PagedQueries/GetPaginatedAllMemberDetails.js
> +							rank: row.rank,
Rank should be computed. I always just did this in the frontend

2023-02-13 05:14 UTC, gabotaco commented on app/graphql/resolvers/PagedQueries/GetPaginatedMemberRankings.js
> +				'rank',
No rank column

2023-02-13 05:14 UTC, gabotaco commented on app/graphql/resolvers/PagedQueries/GetPaginatedMemberRankings.js
> +			order: [['rank', 'ASC']],
No rank column

2023-02-13 05:14 UTC, gabotaco commented on app/graphql/resolvers/PagedQueries/GetPaginatedMemberRankings.js
> +						]
Research graphql's contains operation

2023-02-13 05:14 UTC, gabotaco commented on app/graphql/resolvers/PagedQueries/GetPaginatedMemberRankings.js
> +					rank: rows[i].rank,
Should be computed

2023-02-13 05:14 UTC, gabotaco commented on app/graphql/resolvers/PagedQueries/GetPaginatedWebUsers.js
> +						]
Try graphql's contains

2023-02-13 05:14 UTC, gabotaco commented on app/models/members.js
> +			},
We absolutely cannot have a rank column in the database.

2023-02-13 05:14 UTC, gabotaco commented on app/server.js
> +}
We'd have to run this function every time a member turns in a voucher. That's a lot of updates and why we can't have a rank column

2023-02-16 21:14 UTC, TheGamerzs commented on app/graphql/resolvers/PagedQueries/GetPaginatedMemberRankings.js
> +						]
None appropriate for SQL

2023-02-16 23:27 UTC, rhit-corridg requested changes

2023-02-16 23:27 UTC, rhit-corridg commented on app/graphql/resolvers/MemberQueries/GetMemberRankings.js
> +	console.time('getMemberRankings');
debug log

2023-02-16 23:27 UTC, rhit-corridg commented on app/graphql/resolvers/MemberQueries/GetMemberRankings.js
> +			console.timeEnd('getMemberRankings');
debug log

2023-02-16 23:40 UTC, rhit-corridg approved these changes

2023-02-17 01:04 UTC, merged